### ISSUE TITLE
It only deduplicates injections if register is called with the same js/css object

### ISSUE THREAD

**Issue by fregante** [fregante/content-scripts-register-polyfill#24]
```js
contentScript.register({
	js: ['a.js', 'b.js']
});

contentScript.register({
	js: ['b.js', 'a.js']
});
```

will cause both script to be injected twice because `wasPreviouslyLoaded` uses the whole object, as is, to detect injection.

This is generally avoidable, but it's still a bug.

**Comment by twschiller** [comment]
> This is generally avoidable

The correct behavior is probably to check per file?

**Comment by fregante** [comment]
That's right. Instead of a simple Boolean it should return a list of previously-loaded files.

**Comment by fregante** [comment]
This matches the native API’s behavior, they don't do any deduplication. See:

```js
function register() {
  browser.contentScripts.register({
    matches: ['https://github.com/*'],
    js: [{file:'a.js'}]
  })
}

register();
register();
```


 The only reason why this polyfill has it is because the code was carried over for half a decade, it's possible that it's not necessary anymore: https://github.com/fregante/content-scripts-register-polyfill/issues/28#issuecomment-873927032
