### ISSUE TITLE
Add standalone bundle in npm package

### ISSUE THREAD

**Issue by regseb** [fregante/content-scripts-register-polyfill#34]
Hi,

Can you add a standalone bundle in the package hosted in npm? This way we can easily use your library in a project without a bundler module (like Rollup or Webpack). In my project, I simply [copy](https://github.com/regseb/gout/blob/master/.script/sync.js#L18-L19) the files in extension source.

**Comment by fregante** [comment]
Thanks for the request but my solution to this has been the online bundler. It's not practical to include built files on npm as more than doubles the size of each package
