### ISSUE TITLE
Content script doesn't inject on page load from shorthand url

### ISSUE THREAD

**Issue by twschiller** [fregante/content-scripts-register-polyfill#71]
Step to Reproduce
---
- Version 3.2.2 (imported via webext-dynamic-content-scripts version 9.2.2)
- Grant optional permissions to `https://www.linkedin.com/*`
- Open a new tab and type: linkedin.com
- If you're logged in, page will redirect to https://www.linkedin.com/feed/
- Content script is not injected 😞 

Discussion/Investigation
---
- `browser.webNavigation.onHistoryStateUpdated` is fired for the frame
- `browser.webNavigation.onCommitted` is fired for the frame: 
![image](https://github.com/fregante/content-scripts-register-polyfill/assets/1879821/6b9b108f-e969-4b86-9a3f-859924a9a306)
- ~~Somehow `previouslyLoaded` is coming back as true~~: my debug logging might have messed this up. It's confusing that `wasPreviouslyLoaded` mutates the state
- There's something fishy going on with the frameIds/variable namespace. Somehow `https://www.linkedin.com` first appears as being in a frame, and then the top-level inject fails due to `wasPreviouslyLoaded` coming back as true
 
![image](https://github.com/fregante/content-scripts-register-polyfill/assets/1879821/cecd85ef-97f2-4e8e-9414-74ec30877183)

- The bug appears to be fixed if I pass  tabId and frameId in the wasPreviouslyLoaded check
```
|| await wasPreviouslyLoaded({ tabId, frameId }, { js, css, tabId, frameId }) // Avoid double-injection
```

Other History
---
- The history includes the SPA redirect to /feed/
 ![image](https://github.com/fregante/content-scripts-register-polyfill/assets/1879821/bef799db-e993-4d23-b49c-1e3b1970249d)

Related
---
- https://github.com/fregante/content-scripts-register-polyfill/pull/60

**Comment by fregante** [comment]
This was likely resolved by https://github.com/fregante/content-scripts-register-polyfill/releases/tag/v4.0.0 because `wasPreviouslyLoaded` no longer exists
